<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Practical 3 Normal distribution | H2 Data Science Practical Series</title>
  <meta name="description" content="Handbook for the H2 Data Science practicals." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Practical 3 Normal distribution | H2 Data Science Practical Series" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="https://brightspace.uhi.ac.uk/d2l/home/341332/figs/cover_short.png" />
  <meta property="og:description" content="Handbook for the H2 Data Science practicals." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Practical 3 Normal distribution | H2 Data Science Practical Series" />
  
  <meta name="twitter:description" content="Handbook for the H2 Data Science practicals." />
  <meta name="twitter:image" content="https://brightspace.uhi.ac.uk/d2l/home/341332/figs/cover_short.png" />




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="binpois.html"/>
<link rel="next" href="t-test.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">H2 Data Science Practical Series</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="overview.html"><a href="overview.html"><i class="fa fa-check"></i>Overview</a>
<ul>
<li class="chapter" data-level="0.1" data-path="overview.html"><a href="overview.html#practical-sessions"><i class="fa fa-check"></i><b>0.1</b> Practical sessions</a></li>
<li class="chapter" data-level="0.2" data-path="overview.html"><a href="overview.html#assessments"><i class="fa fa-check"></i><b>0.2</b> Assessments</a></li>
<li class="chapter" data-level="0.3" data-path="overview.html"><a href="overview.html#R_intro"><i class="fa fa-check"></i><b>0.3</b> Getting started in R</a>
<ul>
<li class="chapter" data-level="0.3.1" data-path="overview.html"><a href="overview.html#rstudio-project"><i class="fa fa-check"></i><b>0.3.1</b> RStudio Project</a></li>
<li class="chapter" data-level="0.3.2" data-path="overview.html"><a href="overview.html#rstudio-settings"><i class="fa fa-check"></i><b>0.3.2</b> RStudio Settings</a></li>
<li class="chapter" data-level="0.3.3" data-path="overview.html"><a href="overview.html#r-packages-and-libraries"><i class="fa fa-check"></i><b>0.3.3</b> R packages and libraries</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="1" data-path="EDA.html"><a href="EDA.html"><i class="fa fa-check"></i><b>1</b> Displaying and summarising data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="EDA.html"><a href="EDA.html#basic-data-exploration"><i class="fa fa-check"></i><b>1.1</b> Basic data exploration</a></li>
<li class="chapter" data-level="1.2" data-path="EDA.html"><a href="EDA.html#graphical-methods-for-displaying-data"><i class="fa fa-check"></i><b>1.2</b> Graphical methods for displaying data</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="EDA.html"><a href="EDA.html#scatter-plot"><i class="fa fa-check"></i><b>1.2.1</b> Scatter plot</a></li>
<li class="chapter" data-level="1.2.2" data-path="EDA.html"><a href="EDA.html#boxplots"><i class="fa fa-check"></i><b>1.2.2</b> Boxplots</a></li>
<li class="chapter" data-level="1.2.3" data-path="EDA.html"><a href="EDA.html#line-plots"><i class="fa fa-check"></i><b>1.2.3</b> Line plots</a></li>
<li class="chapter" data-level="1.2.4" data-path="EDA.html"><a href="EDA.html#histograms"><i class="fa fa-check"></i><b>1.2.4</b> Histograms</a></li>
<li class="chapter" data-level="1.2.5" data-path="EDA.html"><a href="EDA.html#bar-graphs"><i class="fa fa-check"></i><b>1.2.5</b> Bar graphs</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="EDA.html"><a href="EDA.html#summary-statistics"><i class="fa fa-check"></i><b>1.3</b> Summary statistics</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="EDA.html"><a href="EDA.html#which-measure-of-central-tendency-to-use"><i class="fa fa-check"></i><b>1.3.1</b> Which measure of central tendency to use</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="EDA.html"><a href="EDA.html#conclusions"><i class="fa fa-check"></i><b>1.4</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="binpois.html"><a href="binpois.html"><i class="fa fa-check"></i><b>2</b> Binomial &amp; Poisson distributions</a>
<ul>
<li class="chapter" data-level="2.1" data-path="binpois.html"><a href="binpois.html#the-binomial-distribution"><i class="fa fa-check"></i><b>2.1</b> The Binomial distribution</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="binpois.html"><a href="binpois.html#bernoulli-trials"><i class="fa fa-check"></i><b>2.1.1</b> Bernoulli trials</a></li>
<li class="chapter" data-level="2.1.2" data-path="binpois.html"><a href="binpois.html#the-binomial-distribution-1"><i class="fa fa-check"></i><b>2.1.2</b> The binomial distribution</a></li>
<li class="chapter" data-level="2.1.3" data-path="binpois.html"><a href="binpois.html#binomial-distributions-by-hand"><i class="fa fa-check"></i><b>2.1.3</b> Binomial distributions by hand</a></li>
<li class="chapter" data-level="2.1.4" data-path="binpois.html"><a href="binpois.html#binomial-distributions-in-r"><i class="fa fa-check"></i><b>2.1.4</b> Binomial distributions in R</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="binpois.html"><a href="binpois.html#the-poisson-distribution"><i class="fa fa-check"></i><b>2.2</b> The Poisson distribution</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="binpois.html"><a href="binpois.html#poisson-distributions-by-hand"><i class="fa fa-check"></i><b>2.2.1</b> Poisson distributions by hand</a></li>
<li class="chapter" data-level="2.2.2" data-path="binpois.html"><a href="binpois.html#poisson-distributions-in-r"><i class="fa fa-check"></i><b>2.2.2</b> Poisson distributions in R</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="binpois.html"><a href="binpois.html#the-poisson-approximation-of-the-binomial-model"><i class="fa fa-check"></i><b>2.3</b> The Poisson approximation of the binomial model</a></li>
<li class="chapter" data-level="2.4" data-path="binpois.html"><a href="binpois.html#conclusions-1"><i class="fa fa-check"></i><b>2.4</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="normal.html"><a href="normal.html"><i class="fa fa-check"></i><b>3</b> Normal distribution</a>
<ul>
<li class="chapter" data-level="3.1" data-path="normal.html"><a href="normal.html#using-the-normal-probability-distributions"><i class="fa fa-check"></i><b>3.1</b> Using the normal probability distributions</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="normal.html"><a href="normal.html#using-r-to-calculate-areas-under-the-normal-curve"><i class="fa fa-check"></i><b>3.1.1</b> Using R to calculate areas under the normal curve</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="normal.html"><a href="normal.html#normal-model-adequacy"><i class="fa fa-check"></i><b>3.2</b> Normal model adequacy</a></li>
<li class="chapter" data-level="3.3" data-path="normal.html"><a href="normal.html#calculating-quantiles-in-the-normal-distribution"><i class="fa fa-check"></i><b>3.3</b> Calculating quantiles in the normal distribution</a></li>
<li class="chapter" data-level="3.4" data-path="normal.html"><a href="normal.html#testing-for-normality"><i class="fa fa-check"></i><b>3.4</b> Testing for normality</a></li>
<li class="chapter" data-level="3.5" data-path="normal.html"><a href="normal.html#transformations"><i class="fa fa-check"></i><b>3.5</b> Data transformations</a></li>
<li class="chapter" data-level="3.6" data-path="normal.html"><a href="normal.html#functions-in-r"><i class="fa fa-check"></i><b>3.6</b> Functions in R</a></li>
<li class="chapter" data-level="3.7" data-path="normal.html"><a href="normal.html#the-central-limit-theorem"><i class="fa fa-check"></i><b>3.7</b> The central limit theorem</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="normal.html"><a href="normal.html#the-distribution-of-means-from-various-data-distributions"><i class="fa fa-check"></i><b>3.7.1</b> The distribution of means from various data distributions</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="normal.html"><a href="normal.html#the-standard-error-of-the-mean"><i class="fa fa-check"></i><b>3.8</b> The standard error of the mean</a></li>
<li class="chapter" data-level="3.9" data-path="normal.html"><a href="normal.html#normal-approximations-for-other-distributions"><i class="fa fa-check"></i><b>3.9</b> Normal approximations for other distributions</a>
<ul>
<li class="chapter" data-level="3.9.1" data-path="normal.html"><a href="normal.html#the-normal-approximation-of-the-poisson-distribution"><i class="fa fa-check"></i><b>3.9.1</b> The Normal approximation of the Poisson distribution</a></li>
<li class="chapter" data-level="3.9.2" data-path="normal.html"><a href="normal.html#the-normal-approximation-of-the-binomial-distribution"><i class="fa fa-check"></i><b>3.9.2</b> The normal approximation of the binomial distribution</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="normal.html"><a href="normal.html#conclusions-2"><i class="fa fa-check"></i><b>3.10</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="t-test.html"><a href="t-test.html"><i class="fa fa-check"></i><b>4</b> t-tests &amp; confidence intervals</a>
<ul>
<li class="chapter" data-level="4.1" data-path="t-test.html"><a href="t-test.html#single-sample-t-tests"><i class="fa fa-check"></i><b>4.1</b> Single sample t-tests</a></li>
<li class="chapter" data-level="4.2" data-path="t-test.html"><a href="t-test.html#confidence-intervals"><i class="fa fa-check"></i><b>4.2</b> Confidence Intervals</a></li>
<li class="chapter" data-level="4.3" data-path="t-test.html"><a href="t-test.html#comparing-means-two-sample-t-tests"><i class="fa fa-check"></i><b>4.3</b> Comparing means (two-sample t tests)</a></li>
<li class="chapter" data-level="4.4" data-path="t-test.html"><a href="t-test.html#non-parametric-tests"><i class="fa fa-check"></i><b>4.4</b> Non-parametric Tests</a></li>
<li class="chapter" data-level="4.5" data-path="t-test.html"><a href="t-test.html#conclusions-3"><i class="fa fa-check"></i><b>4.5</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="glm.html"><a href="glm.html"><i class="fa fa-check"></i><b>5</b> General Linear Models</a>
<ul>
<li class="chapter" data-level="5.1" data-path="glm.html"><a href="glm.html#analysis-of-variance-anova"><i class="fa fa-check"></i><b>5.1</b> Analysis of variance (ANOVA)</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="glm.html"><a href="glm.html#anova-in-r"><i class="fa fa-check"></i><b>5.1.1</b> ANOVA in R</a></li>
<li class="chapter" data-level="5.1.2" data-path="glm.html"><a href="glm.html#one-way-anova"><i class="fa fa-check"></i><b>5.1.2</b> One-way ANOVA</a></li>
<li class="chapter" data-level="5.1.3" data-path="glm.html"><a href="glm.html#two-way-anova"><i class="fa fa-check"></i><b>5.1.3</b> Two-way ANOVA</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="glm.html"><a href="glm.html#regression"><i class="fa fa-check"></i><b>5.2</b> Regression</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="glm.html"><a href="glm.html#overview-1"><i class="fa fa-check"></i><b>5.2.1</b> Overview</a></li>
<li class="chapter" data-level="5.2.2" data-path="glm.html"><a href="glm.html#linear-regression-in-r"><i class="fa fa-check"></i><b>5.2.2</b> Linear regression in R</a></li>
<li class="chapter" data-level="5.2.3" data-path="glm.html"><a href="glm.html#plotting-the-regression-line-and-confidence-intervals"><i class="fa fa-check"></i><b>5.2.3</b> Plotting the regression line and confidence intervals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="glm.html"><a href="glm.html#conclusions-4"><i class="fa fa-check"></i><b>5.3</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="multivariate.html"><a href="multivariate.html"><i class="fa fa-check"></i><b>6</b> Multivariate analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="multivariate.html"><a href="multivariate.html#multivariate-analysis-in-r"><i class="fa fa-check"></i><b>6.1</b> Multivariate analysis in R</a></li>
<li class="chapter" data-level="6.2" data-path="multivariate.html"><a href="multivariate.html#diversity-indices"><i class="fa fa-check"></i><b>6.2</b> Diversity indices</a></li>
<li class="chapter" data-level="6.3" data-path="multivariate.html"><a href="multivariate.html#nmds-on-real-data"><i class="fa fa-check"></i><b>6.3</b> NMDS on real data</a></li>
<li class="chapter" data-level="6.4" data-path="multivariate.html"><a href="multivariate.html#principal-components-analysis-pca"><i class="fa fa-check"></i><b>6.4</b> Principal components analysis (PCA)</a></li>
<li class="chapter" data-level="6.5" data-path="multivariate.html"><a href="multivariate.html#conclusions-5"><i class="fa fa-check"></i><b>6.5</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="appendix.html"><a href="appendix.html"><i class="fa fa-check"></i><b>7</b> Appendix</a>
<ul>
<li class="chapter" data-level="7.1" data-path="appendix.html"><a href="appendix.html#probability"><i class="fa fa-check"></i><b>7.1</b> Probability</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="appendix.html"><a href="appendix.html#probability-for-equally-likely-outcomes"><i class="fa fa-check"></i><b>7.1.1</b> Probability for equally likely outcomes</a></li>
<li class="chapter" data-level="7.1.2" data-path="appendix.html"><a href="appendix.html#multiplication-and-addition"><i class="fa fa-check"></i><b>7.1.2</b> Multiplication and addition</a></li>
<li class="chapter" data-level="7.1.3" data-path="appendix.html"><a href="appendix.html#bayes-theorem"><i class="fa fa-check"></i><b>7.1.3</b> Bayes’ theorem</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="appendix.html"><a href="appendix.html#univariate-statistics"><i class="fa fa-check"></i><b>7.2</b> Univariate statistics</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="appendix.html"><a href="appendix.html#mean"><i class="fa fa-check"></i><b>7.2.1</b> Mean</a></li>
<li class="chapter" data-level="7.2.2" data-path="appendix.html"><a href="appendix.html#median-quartiles-and-adjacent-values"><i class="fa fa-check"></i><b>7.2.2</b> Median, quartiles and adjacent values</a></li>
<li class="chapter" data-level="7.2.3" data-path="appendix.html"><a href="appendix.html#the-sum-of-squares"><i class="fa fa-check"></i><b>7.2.3</b> The sum of squares</a></li>
<li class="chapter" data-level="7.2.4" data-path="appendix.html"><a href="appendix.html#measures-of-dispersion"><i class="fa fa-check"></i><b>7.2.4</b> Measures of dispersion</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="appendix.html"><a href="appendix.html#the-binomial-distribution-2"><i class="fa fa-check"></i><b>7.3</b> The Binomial distribution</a></li>
<li class="chapter" data-level="7.4" data-path="appendix.html"><a href="appendix.html#the-poisson-distribution-1"><i class="fa fa-check"></i><b>7.4</b> The Poisson distribution</a></li>
<li class="chapter" data-level="7.5" data-path="appendix.html"><a href="appendix.html#z-scores"><i class="fa fa-check"></i><b>7.5</b> Z scores</a></li>
<li class="chapter" data-level="7.6" data-path="appendix.html"><a href="appendix.html#samples-taken-from-a-population"><i class="fa fa-check"></i><b>7.6</b> Samples taken from a population</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="appendix.html"><a href="appendix.html#standard-error-of-the-mean"><i class="fa fa-check"></i><b>7.6.1</b> Standard error of the mean</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="appendix.html"><a href="appendix.html#the-t-distribution"><i class="fa fa-check"></i><b>7.7</b> The t distribution</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="appendix.html"><a href="appendix.html#the-one-sample-t-test"><i class="fa fa-check"></i><b>7.7.1</b> The one sample t-test</a></li>
<li class="chapter" data-level="7.7.2" data-path="appendix.html"><a href="appendix.html#confidence-intervals-for-sample-means"><i class="fa fa-check"></i><b>7.7.2</b> Confidence intervals for sample means</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="appendix.html"><a href="appendix.html#anova"><i class="fa fa-check"></i><b>7.8</b> ANOVA</a></li>
<li class="chapter" data-level="7.9" data-path="appendix.html"><a href="appendix.html#regression-correlation"><i class="fa fa-check"></i><b>7.9</b> Regression &amp; correlation</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">H2 Data Science Practical Series</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="normal" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Practical 3</span> Normal distribution<a href="normal.html#normal" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Statistical inference is the process by which we infer from a sample statistic to the population. We need to infer from samples to populations because it is usually impossible to measure the entire populations. We call this this estimating population parameters from samples.</p>
<p>In order to infer from samples to populations we need to understand/predict how the statistics we generate from our samples ‘behave’. To do this we use theoretical distributions.</p>
<p><em>Q71. Which two theoretical distributions have we already covered in this course?</em></p>
<p>The normal (a.k.a., Gaussian) distribution is another theoretical distribution and is central to inferential statistics. If your data (or, more accuarately, statistics derived from you data) are reasonably approximated by the normal distribution then you will be able to use a wide range of techniques to deal with it.</p>
<p>In this practical we will be examining the normal distribution, calculating Z scores both manually and in R, and interpreting those Z scores. We’ll also use our knowledge of the normal distribution’s behaviour to produce confidence intervals and assess whether data are reasonably assummed to be normally distributed, transforming the data where they are not. We’ll apply the CLT and evaluate how well other distributions are approximated by the normal distribution.</p>
<hr />
<div id="using-the-normal-probability-distributions" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Using the normal probability distributions<a href="normal.html#using-the-normal-probability-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The length, in cm, of a catch of herring was measured. Five hundred individuals were studied. We will consider this group to be the entire population of interest. The population parameters are: mean length 37.6 cm, standard deviation 1.20 cm.</p>
<p><em>Q72. What are the theoretical limits of the normal distribution?</em></p>
<p><em>Q73. Do you think normality a fair assumption for these data?</em></p>
<p><em>Q74. Assume length of herring is approximately normally distributed and write down the model which describes the fish length distribution in the standard notation.</em></p>
<p>When we have population parameters such as we have here, we can calculate Z scores for individuals (or groups of individuals) from that population and calculate how unusual they are. For the moment, we are interested in determining what proportion of fish from this population expected to be &lt;38cm.</p>
<p><em>Q75. Sketch a normal distribution, showing mean of 37.6cm, note the sd on your sketch and sketch on the location of a fish at 38 cm.</em></p>
<p><em>Q76. Mark-out the bit of the sketch which the question asks you about</em></p>
<p><em>Q77. Mark out the bit of the sketch that our manually determined Z scores relate to.</em></p>
<p><em>Q78. Calculate the Z score for a fish of 38cm. How unusual is such an observation? What proportion of fish will be &lt;38 cm, what proportion of fish &gt;38 cm?.</em></p>
<div id="using-r-to-calculate-areas-under-the-normal-curve" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Using R to calculate areas under the normal curve<a href="normal.html#using-r-to-calculate-areas-under-the-normal-curve" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To solve this problem using R we use cumulative probability. Observations at the extreme low end are extremely unlikely, but the probability of observing data increases and reaches a maximum at the mean, after which it declines again. The normal distribution is symmetrical.</p>
<p><em>Q79. What shape is the cumulative probability curve of a normally distributed variable?</em></p>
<p>You can ask R to determine the probabilities of an eventuality occurring within a normal distribution. For example, you could ask what the probability is of observing a 38 cm or more fish, when the mean is 37.6 cm and the standard deviation is 1.20 cm. You need to specify the model, and the problem. Use <code>?dnorm</code> and look at your options.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="normal.html#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cumulative probability: which bit of the curve does this relate to?</span></span>
<span id="cb141-2"><a href="normal.html#cb141-2" aria-hidden="true" tabindex="-1"></a><span class="fu">pnorm</span>(<span class="at">q =</span> <span class="dv">38</span>, <span class="at">mean =</span> <span class="fl">37.6</span>, <span class="at">sd =</span> <span class="fl">1.2</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:dpq-examp"></span>
<img src="_main_files/figure-html/dpq-examp-1.png" alt="Functions for distributions in R illustrated with a standard normal." width="80%" height="80%" />
<p class="caption">
Figure 3.1: Functions for distributions in R illustrated with a standard normal.
</p>
</div>
<p>We can plot any normal distribution we like. Play with the values for <code>mu</code> and <code>sigma</code> below, adjusting the values for <code>from</code> and <code>to</code> as needed to see the distribution.</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="normal.html#cb142-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fl">37.6</span>  <span class="co"># population mean</span></span>
<span id="cb142-2"><a href="normal.html#cb142-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">1.2</span>  <span class="co"># population sd</span></span>
<span id="cb142-3"><a href="normal.html#cb142-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean =</span> mu, <span class="at">sd =</span> sigma), <span class="at">from =</span> <span class="dv">30</span>, <span class="at">to =</span> <span class="dv">45</span>,</span>
<span id="cb142-4"><a href="normal.html#cb142-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">main =</span> <span class="st">&quot;Normal density&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Density&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Fish length, cm&quot;</span>)</span></code></pre></div>
<p>I can define a population like this <span class="math inline">\(y \sim Norm(37.6, 1.2)\)</span> and ask questions about <span class="math inline">\(P(y_i \leq a)\)</span>. E.g., what is the probability that a random fish drawn from this population is &lt;38 cm (<span class="math inline">\(P(y_i &lt; 38)\)</span>). The answer to that is 0.6306 or approximately 63% (2 sf).</p>
<p><em>Q80. How does your hand calculation compare? Is there a discrepancy? If so, why?</em></p>
<hr />
</div>
</div>
<div id="normal-model-adequacy" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Normal model adequacy<a href="normal.html#normal-model-adequacy" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A separate fish population (long-eared wrasse) is described as <span class="math inline">\(y \sim Norm(5.14 cm, 25 cm)\)</span>.</p>
<p><em>Q81. What is the mean length and standard deviation of long-eared wrasse?</em></p>
<p><em>Q82. Calculate the proportion of fish that are less than zero cm in length.</em></p>
<p><em>Q84. What do your results indicate about the adequacy of the normal model to describe the length distribution of long-eared wrasse?</em></p>
<p><em>Q85. Recalculate your answers with 1/10<sup>th</sup> the standard deviation:</em> <span class="math inline">\(y \sim Norm(5.14, 2.5)\)</span><em>.</em></p>
<hr />
</div>
<div id="calculating-quantiles-in-the-normal-distribution" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Calculating quantiles in the normal distribution<a href="normal.html#calculating-quantiles-in-the-normal-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A quantile is one of a series of values that divides a frequency distribution (i.e. a set of numbers) into equally represented groups (i.e., the same number of observations per group). For example, there are three values (Q1, Q2, Q3) that split a normal distribution into four groups (negative infinity to Q1, Q1 to Q2 (median), Q2 to Q3, and Q3 to positive infinity). Q3 - Q2 is the middle 50% of the data: the interquartile range.</p>
<p>There are 99 quantiles, called percentiles, that split your data into 100 groups. The 2.5 percentile is the value that splits your data into two groups corresponding to 2.5% along the distribution (from negative infinity for the normal distribution). Just as we can ask what proportion of a distribution is above or below a set value, we can also ask between what values will a given percentage of my data lie (e.g. what values correspond to the middle 95%?).</p>
<p>To solve this problem using R we use the cumulative probability function <code>qnorm()</code>.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="normal.html#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> <span class="fl">0.975</span>, <span class="at">mean =</span> <span class="fl">37.6</span>, <span class="at">sd =</span> <span class="fl">1.2</span>) <span class="co"># p is the cumulative probability </span></span></code></pre></div>
<pre><code>## [1] 39.95196</code></pre>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="normal.html#cb145-1" aria-hidden="true" tabindex="-1"></a>probs <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="fl">0.1</span>, <span class="at">to =</span> <span class="fl">0.9</span>, <span class="at">by =</span> <span class="fl">0.2</span>) <span class="co"># vectorize for &gt;1 probability</span></span>
<span id="cb145-2"><a href="normal.html#cb145-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> probs, <span class="at">mean =</span> <span class="fl">37.6</span>, <span class="at">sd =</span> <span class="fl">1.2</span>) </span></code></pre></div>
<pre><code>## [1] 36.06214 36.97072 37.60000 38.22928 39.13786</code></pre>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="normal.html#cb147-1" aria-hidden="true" tabindex="-1"></a>probs_95 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.975</span>) <span class="co"># middle 95% (2.5% on either side)</span></span>
<span id="cb147-2"><a href="normal.html#cb147-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qnorm</span>(<span class="at">p =</span> probs_95, <span class="at">mean =</span> <span class="fl">37.6</span>, <span class="at">sd =</span> <span class="fl">1.2</span>) <span class="co"># round as appropriate</span></span></code></pre></div>
<pre><code>## [1] 35.24804 39.95196</code></pre>
<p>These values (<code>probs_95 = c(0.025, 0.975)</code>) identify proportions of the cumulative curve. That is, they identify the bottom 2.5% and the bottom 97.5% of the curve. Values between these two parameters will constitute the central 95% of your data.</p>
<p>For the next question, return to the herring data where the population was <span class="math inline">\(y \sim Norm(37.6, 1.44)\)</span>.</p>
<p><em>Q86. Find the values that capture the middle 95 and 90% of the herring data.</em></p>
<p>We quote our mean and interval like this: “The mean fish length and 95% interval was 37.6 cm (35.2 cm, 40.0 cm)”. Remember to use to same degree of precision (significant figures) for confidence intervals as was used to gather the data (or as specified in the question, defaulting to three).</p>
<p><em>Q87. What value would you expect to correspond to 0.5 (i.e., what value would be found half-way along your distribution)?</em></p>
<p><em>Q88. Check your answer above using <code>qnorm()</code></em></p>
<p>You can easily visualise this distribution in R:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="normal.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="co"># your population is defined thus: y ~ Norm(mean=100, variance=225) </span></span>
<span id="cb149-2"><a href="normal.html#cb149-2" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb149-3"><a href="normal.html#cb149-3" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">15</span></span>
<span id="cb149-4"><a href="normal.html#cb149-4" aria-hidden="true" tabindex="-1"></a><span class="co"># lower boundary and upper boundary of the region of interest</span></span>
<span id="cb149-5"><a href="normal.html#cb149-5" aria-hidden="true" tabindex="-1"></a>lb <span class="ot">&lt;-</span> <span class="dv">80</span></span>
<span id="cb149-6"><a href="normal.html#cb149-6" aria-hidden="true" tabindex="-1"></a>ub <span class="ot">&lt;-</span> <span class="dv">140</span> </span>
<span id="cb149-7"><a href="normal.html#cb149-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb149-8"><a href="normal.html#cb149-8" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="at">length.out =</span> <span class="dv">100</span>) <span class="sc">*</span> sigma <span class="sc">+</span> mu</span>
<span id="cb149-9"><a href="normal.html#cb149-9" aria-hidden="true" tabindex="-1"></a>hx <span class="ot">&lt;-</span> <span class="fu">dnorm</span>(x, mu, sigma)</span>
<span id="cb149-10"><a href="normal.html#cb149-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, hx,</span>
<span id="cb149-11"><a href="normal.html#cb149-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">&quot;n&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;IQ Values&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb149-12"><a href="normal.html#cb149-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">&quot;Normal Distribution&quot;</span>, <span class="at">axes =</span> <span class="cn">FALSE</span></span>
<span id="cb149-13"><a href="normal.html#cb149-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb149-14"><a href="normal.html#cb149-14" aria-hidden="true" tabindex="-1"></a>i <span class="ot">&lt;-</span> x <span class="sc">&gt;=</span> lb <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> ub</span>
<span id="cb149-15"><a href="normal.html#cb149-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x, hx)</span>
<span id="cb149-16"><a href="normal.html#cb149-16" aria-hidden="true" tabindex="-1"></a><span class="fu">polygon</span>(<span class="fu">c</span>(lb, x[i], ub), <span class="fu">c</span>(<span class="dv">0</span>, hx[i], <span class="dv">0</span>), <span class="at">col =</span> <span class="st">&quot;red&quot;</span>) <span class="co"># create 100 polygons</span></span>
<span id="cb149-17"><a href="normal.html#cb149-17" aria-hidden="true" tabindex="-1"></a>area <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(ub, mu, sigma) <span class="sc">-</span> <span class="fu">pnorm</span>(lb, mu, sigma)</span>
<span id="cb149-18"><a href="normal.html#cb149-18" aria-hidden="true" tabindex="-1"></a>result <span class="ot">&lt;-</span> <span class="fu">paste</span>(</span>
<span id="cb149-19"><a href="normal.html#cb149-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;P(&quot;</span>, lb, <span class="st">&quot;&lt; IQ &lt;&quot;</span>, ub, <span class="st">&quot;) =&quot;</span>,</span>
<span id="cb149-20"><a href="normal.html#cb149-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">signif</span>(area, <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb149-21"><a href="normal.html#cb149-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb149-22"><a href="normal.html#cb149-22" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(result, <span class="dv">3</span>)</span>
<span id="cb149-23"><a href="normal.html#cb149-23" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="fu">seq</span>(<span class="fu">floor</span>(mu <span class="sc">-</span> <span class="dv">4</span><span class="sc">*</span>sigma), <span class="fu">floor</span>(mu <span class="sc">+</span> <span class="dv">4</span><span class="sc">*</span>sigma), sigma), <span class="at">pos =</span> <span class="dv">0</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:iq-examp"></span>
<img src="_main_files/figure-html/iq-examp-1.png" alt="The normal distribution illustrating probability of a random individual from your population having an IQ between 80 and 140." width="60%" height="60%" />
<p class="caption">
Figure 3.2: The normal distribution illustrating probability of a random individual from your population having an IQ between 80 and 140.
</p>
</div>
<p><em>Q89. Change the parameters in the above to your herring data where the population was distributed</em> <span class="math inline">\(y \sim Norm(37.6, 1.44)\)</span> <em>and check that the values you generated for the 95% interval correspond when plugged into <code>lb</code> and <code>ub</code> in the code.</em></p>
<p><em>Q90. What is the difference between</em> <span class="math inline">\(&lt; x\)</span> <em>and</em> <span class="math inline">\(\leq x\)</span> <em>when applied to continuous data?</em></p>
<p><em>Q91. Does this also apply to discontinuous data?</em></p>
<p>Think about how intervals change when the population standard deviation changes.</p>
<p><em>Q92. With everything else equal, try doubling, quadrupling, and halving the standard deviation on the herring data then re-running the same code.</em></p>
<p><em>Q93. What effect does this have on your interval?</em></p>
<hr />
</div>
<div id="testing-for-normality" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Testing for normality<a href="normal.html#testing-for-normality" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>As we note in the lectures, many statistical tests require that data are reasonably approximated by a normal distribution and have homogeneous variance. R can be used to formally test the assumption that data are normally distributed, though you should have some idea of whether this is likely through consideration of the data source. This applies particularly where you have a small sample size and, consequently, evaluating the distribution is challenging.</p>
<p>The data you collect will be part of a population. The normality check assesses the viability of the assumption that the data you collected were drawn from a population that was normally distributed. You should note that populations are, in practice, <em>never</em> actually normally distributed. Your test is to assess how <em>reasonable</em> the assumption of normality is.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="normal.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl) </span>
<span id="cb150-2"><a href="normal.html#cb150-2" aria-hidden="true" tabindex="-1"></a>MS <span class="ot">&lt;-</span> <span class="fu">read_xlsx</span>(<span class="st">&quot;data/practical_3_4.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;Mood shrimp&quot;</span>)</span>
<span id="cb150-3"><a href="normal.html#cb150-3" aria-hidden="true" tabindex="-1"></a><span class="co"># check the data using head(), str() etc.</span></span></code></pre></div>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="normal.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb151-2"><a href="normal.html#cb151-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(MS<span class="sc">$</span>Shrimp1)</span>
<span id="cb151-3"><a href="normal.html#cb151-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(MS<span class="sc">$</span>Shrimp1, <span class="at">col =</span> <span class="dv">2</span>) <span class="co"># the data fall near the line</span></span>
<span id="cb151-4"><a href="normal.html#cb151-4" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(MS<span class="sc">$</span>Shrimp2)</span>
<span id="cb151-5"><a href="normal.html#cb151-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(MS<span class="sc">$</span>Shrimp1, <span class="at">col =</span> <span class="dv">2</span>) <span class="co"># the data deviate widely from the line</span></span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:qq-examp"></span>
<img src="_main_files/figure-html/qq-examp-1.png" alt="Normal (QQ) plots. The left indicates that the normality assumption might be reasonable, not so on the right." width="50%" height="50%" />
<p class="caption">
Figure 3.3: Normal (QQ) plots. The left indicates that the normality assumption might be reasonable, not so on the right.
</p>
</div>
<p>The axes on the probability plots have been rescaled so that, if your data are perfectly normal, the data points would fall on a straight line (the red line on the graphs generated by <code>qqline()</code>). Any deviation from the red straight line in your data indicates a lack of normality. What we need to assess is how serious any deviation is and whether it is sufficient to indicate that the assumption of normality is not ‘reasonable’. This is a subjective decision, and two different statisticians may tell you different answers about the same data.</p>
<p>As your sample size decreases, it will be increasingly difficult to see if your data are reasonably approximated by a normal distribution. There are many formal statistical methods for assessing normality, but as we already know it is impossible for your data to have been drawn from a population that is normal and this means such tests are largely redundant. You must assess the assumptions of your model (e.g. the general linear model, which includes ANOVA and linear regression), but you should be aware that all data fails the assumptions. However, this doesn’t mean the outputs from such models aren’t useful - provided the assumptions are ‘reasonably’ well met. There is no hard rule as to what constitutes ‘reasonable’!</p>
<p><em>Q94. Make histograms of both <code>Shrimp1</code> and <code>Shrimp2</code>. Comment on their apparent distributions.</em></p>
<hr />
</div>
<div id="transformations" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Data transformations<a href="normal.html#transformations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The assumption that our sample data are drawn from a normally distributed population is central to the use of many important inferential statistical techniques. However, frequently it is <em>not</em> reasonable to assume that data are likely to be normally distributed and they ‘fail’ normality tests (e.g. clearly do not fall on the red <code>qqline()</code>).</p>
<p>Non-normality often occurs because our measurements are near a logical zero. For example, chemical concentrations (e.g., of zinc in sediments) is limited by zero; you cannot have negative zinc concentrations. Similarly, you cannot have negative lengths, time, mass, etc. Where data is collected ‘near’ a logical zero they are often not normally distributed, since the normal distribution predicts a negative-value ‘tail’ which is impossible.</p>
<p>There are several simple mathematical transformation options that you can use in an attempt to convert your data to something that is reasonably approximated by a normal distribution even if it is not well approximated in the original measurement units.</p>
<p>Here we will consider three common transformations. These are the log (base 10 or natural), the square-root, and the arcsine transformation. These transformations often have the additional benefit of correcting unequal variances (see Practical <a href="glm.html#glm">5</a>) in addition to non-normality so they are very useful. These three are often used in distinct circumstances.</p>
<ul>
<li>Log (<code>log()</code>): When the distribution is skewed right. Often ‘cures’ heteroscedasticity.<br />
</li>
<li>Square-root (<code>sqrt()</code>): When the measurements are areas (e.g., leaf areas). Often used to ‘down-weight’ common species (e.g., Practical <a href="multivariate.html#multivariate">6</a>), which is unrelated to model assumptions.<br />
</li>
<li>Arcsine (<code>asin()</code>): When the measurements are percentages or proportions. Tends to stretch out the tails (e.g., near 0 or 1 for proportions) and squash the middle (e.g., near 0.5).</li>
</ul>
<p>Identifying the correct transformation can be led by an underlying comprehension of the nature of the data. However, this often doesn’t work so expect some trial and error.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="normal.html#cb152-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="dv">100</span>, <span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb152-2"><a href="normal.html#cb152-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.99</span>, <span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb152-3"><a href="normal.html#cb152-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-4"><a href="normal.html#cb152-4" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">mar=</span><span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb152-5"><a href="normal.html#cb152-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(a, a<span class="sc">^</span><span class="fl">0.5</span>, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb152-6"><a href="normal.html#cb152-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(a, <span class="fu">log</span>(a), <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb152-7"><a href="normal.html#cb152-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(a, a<span class="sc">^</span><span class="dv">2</span>, <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb152-8"><a href="normal.html#cb152-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(b, <span class="fu">asin</span>(b), <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb152-9"><a href="normal.html#cb152-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(b, <span class="fu">log</span>(b), <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span>
<span id="cb152-10"><a href="normal.html#cb152-10" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(b, <span class="fu">log10</span>(b), <span class="at">type=</span><span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-58-1.png" width="70%" height="70%" style="display: block; margin: auto;" /></p>
<p><em>Q95. Using the Radon concentration worksheet, plot the data. Do they look normally distributed?</em></p>
<p><em>Q96. In your own time,use R to determine the log, square root, and reciprocals (and combinations of all of them: at least one converts the data to approximate normality).</em></p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="normal.html#cb153-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the Radon data into R; the units are parts per billion</span></span>
<span id="cb153-2"><a href="normal.html#cb153-2" aria-hidden="true" tabindex="-1"></a>readxl<span class="sc">::</span><span class="fu">excel_sheets</span>(<span class="st">&quot;data/practical_3_4.xlsx&quot;</span>) </span></code></pre></div>
<pre><code>##  [1] &quot;Cod lengths&quot;           &quot;Shrimps&quot;               &quot;Caffeine&quot;             
##  [4] &quot;Non-parametric shrimp&quot; &quot;Mood shrimp&quot;           &quot;Mood shrimp2&quot;         
##  [7] &quot;Swimming activity&quot;     &quot;Clare&#39;s Al data&quot;       &quot;Distribution&quot;         
## [10] &quot;Radon (ppb)&quot;           &quot;Zinc conc&quot;             &quot;Heart-beat,2012&quot;      
## [13] &quot;Sheet1&quot;</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="normal.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the dataset and try some transformations</span></span></code></pre></div>
<p><em>Q97. Generate a vector of numbers and then use <code>sqrt()</code> on them.</em></p>
<hr />
</div>
<div id="functions-in-r" class="section level2 hasAnchor" number="3.6">
<h2><span class="header-section-number">3.6</span> Functions in R<a href="normal.html#functions-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Everything that <em>does</em> in R is a function. Writing your own functions has many benefits, including keeping your code legible and reducing work for yourself (since any changes need to be done in only one location instead of everywhere you’ve repeated the same code).</p>
<p>The <code>trim_values</code> function takes an argument (<code>x</code>), formats it to three digits, and returns the formatted output. Play around with the function to see how it works. We’ll use this function to keep our outputted values ‘clean’. In order to use the function, you must run the code defining it first. You will see your functions listed (alongside your dataframes, vectors, lists, etc) in R-Studio’s ‘Environment’ pane.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="normal.html#cb156-1" aria-hidden="true" tabindex="-1"></a>trim_values <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb156-2"><a href="normal.html#cb156-2" aria-hidden="true" tabindex="-1"></a>  y <span class="ot">&lt;-</span> <span class="fu">format</span>(x, <span class="at">digits =</span> <span class="dv">3</span>)</span>
<span id="cb156-3"><a href="normal.html#cb156-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(y)</span>
<span id="cb156-4"><a href="normal.html#cb156-4" aria-hidden="true" tabindex="-1"></a>} </span>
<span id="cb156-5"><a href="normal.html#cb156-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb156-6"><a href="normal.html#cb156-6" aria-hidden="true" tabindex="-1"></a><span class="co"># After running the code above, we can use the function:</span></span>
<span id="cb156-7"><a href="normal.html#cb156-7" aria-hidden="true" tabindex="-1"></a><span class="fu">trim_values</span>(<span class="fl">1.23456</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1.23&quot;</code></pre>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="normal.html#cb158-1" aria-hidden="true" tabindex="-1"></a>long_numbers <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">1</span>)</span>
<span id="cb158-2"><a href="normal.html#cb158-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">orig=</span>long_numbers,</span>
<span id="cb158-3"><a href="normal.html#cb158-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">clean=</span><span class="fu">trim_values</span>(long_numbers))</span></code></pre></div>
<pre><code>##        orig clean
## 1 1.5816433 1.582
## 2 0.9450732 0.945
## 3 2.2338246 2.234</code></pre>
<p>Notice anything strange about the output? The function <code>format()</code> converts the vector from <code>numeric</code> to <code>character</code> to display each value with the same number of characters. The <code>digits=3</code> argument is also taken as a suggestion (kind of like <code>breaks</code> in <code>hist()</code>). Try some of the other options in <code>format()</code> or adjust the <code>digits</code> argument, re-running the function definition each time to see the changes.</p>
<hr />
</div>
<div id="the-central-limit-theorem" class="section level2 hasAnchor" number="3.7">
<h2><span class="header-section-number">3.7</span> The central limit theorem<a href="normal.html#the-central-limit-theorem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The central limit theorem states that <strong>the means of normally distributed data will, themselves, be normally distributed</strong>. In addition, the theorem states that <strong>the means of data which are NOT normally distributed will be normally distributed if the sample size is sufficiently large</strong>. In this practical we are going to demonstrate this theorem using random data generated from various probability distributions.</p>
<div id="the-distribution-of-means-from-various-data-distributions" class="section level3 hasAnchor" number="3.7.1">
<h3><span class="header-section-number">3.7.1</span> The distribution of means from various data distributions<a href="normal.html#the-distribution-of-means-from-various-data-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="normal.html#cb160-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run this code, then adjust the values for obs_data as you like.</span></span>
<span id="cb160-2"><a href="normal.html#cb160-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Play with more distributions if you want: ?stats::distributions</span></span>
<span id="cb160-3"><a href="normal.html#cb160-3" aria-hidden="true" tabindex="-1"></a>obs_data <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">rnorm</span>(<span class="dv">2000</span>, <span class="dv">200</span>, <span class="dv">20</span>), </span>
<span id="cb160-4"><a href="normal.html#cb160-4" aria-hidden="true" tabindex="-1"></a>              <span class="fu">rnorm</span>(<span class="dv">1500</span>, <span class="dv">100</span>, <span class="dv">20</span>), </span>
<span id="cb160-5"><a href="normal.html#cb160-5" aria-hidden="true" tabindex="-1"></a>              <span class="fu">rlnorm</span>(<span class="dv">100</span>, <span class="dv">5</span>, <span class="fl">0.5</span>),</span>
<span id="cb160-6"><a href="normal.html#cb160-6" aria-hidden="true" tabindex="-1"></a>              <span class="fu">rpois</span>(<span class="dv">1000</span>, <span class="dv">15</span>), </span>
<span id="cb160-7"><a href="normal.html#cb160-7" aria-hidden="true" tabindex="-1"></a>              <span class="fu">rpois</span>(<span class="dv">500</span>, <span class="dv">30</span>))</span>
<span id="cb160-8"><a href="normal.html#cb160-8" aria-hidden="true" tabindex="-1"></a>xlims <span class="ot">&lt;-</span> <span class="fu">range</span>(obs_data)</span>
<span id="cb160-9"><a href="normal.html#cb160-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-10"><a href="normal.html#cb160-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Define size of each sample and the number of sampling repeats</span></span>
<span id="cb160-11"><a href="normal.html#cb160-11" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb160-12"><a href="normal.html#cb160-12" aria-hidden="true" tabindex="-1"></a>num_samples <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb160-13"><a href="normal.html#cb160-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-14"><a href="normal.html#cb160-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Sample num_samples times from obs_data, with n = sample_size for each sample</span></span>
<span id="cb160-15"><a href="normal.html#cb160-15" aria-hidden="true" tabindex="-1"></a>sample_means <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="at">length=</span>num_samples) <span class="co"># initialize an empty vector</span></span>
<span id="cb160-16"><a href="normal.html#cb160-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>num_samples) {</span>
<span id="cb160-17"><a href="normal.html#cb160-17" aria-hidden="true" tabindex="-1"></a>  sample_i <span class="ot">&lt;-</span> <span class="fu">sample</span>(obs_data, sample_size, <span class="at">replace=</span>T)</span>
<span id="cb160-18"><a href="normal.html#cb160-18" aria-hidden="true" tabindex="-1"></a>  sample_means[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_i)</span>
<span id="cb160-19"><a href="normal.html#cb160-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb160-20"><a href="normal.html#cb160-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-21"><a href="normal.html#cb160-21" aria-hidden="true" tabindex="-1"></a><span class="co"># plot observed distribution</span></span>
<span id="cb160-22"><a href="normal.html#cb160-22" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb160-23"><a href="normal.html#cb160-23" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>)) </span>
<span id="cb160-24"><a href="normal.html#cb160-24" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(obs_data,</span>
<span id="cb160-25"><a href="normal.html#cb160-25" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">&quot;Raw data distribution&quot;</span>,</span>
<span id="cb160-26"><a href="normal.html#cb160-26" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste0</span>(<span class="st">&quot;mean: &quot;</span>, <span class="fu">trim_values</span>(<span class="fu">mean</span>(obs_data)), </span>
<span id="cb160-27"><a href="normal.html#cb160-27" aria-hidden="true" tabindex="-1"></a>                  <span class="st">&quot;, sd: &quot;</span>, <span class="fu">trim_values</span>(<span class="fu">sd</span>(obs_data))),</span>
<span id="cb160-28"><a href="normal.html#cb160-28" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">xlab =</span> <span class="st">&quot;Observed length (cm)&quot;</span>, <span class="at">xlim =</span> xlims</span>
<span id="cb160-29"><a href="normal.html#cb160-29" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb160-30"><a href="normal.html#cb160-30" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(obs_data, <span class="at">main =</span> <span class="st">&quot;Raw data QQ&quot;</span>)</span>
<span id="cb160-31"><a href="normal.html#cb160-31" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(obs_data)</span>
<span id="cb160-32"><a href="normal.html#cb160-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-33"><a href="normal.html#cb160-33" aria-hidden="true" tabindex="-1"></a><span class="co"># plot distribution of sample means</span></span>
<span id="cb160-34"><a href="normal.html#cb160-34" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(sample_means,</span>
<span id="cb160-35"><a href="normal.html#cb160-35" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="fu">paste0</span>(<span class="st">&quot;Sample distribution, N: &quot;</span>, sample_size),</span>
<span id="cb160-36"><a href="normal.html#cb160-36" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste0</span>(<span class="st">&quot;mean: &quot;</span>, <span class="fu">trim_values</span>(<span class="fu">mean</span>(sample_means)), </span>
<span id="cb160-37"><a href="normal.html#cb160-37" aria-hidden="true" tabindex="-1"></a>                  <span class="st">&quot;, sd: &quot;</span>, <span class="fu">trim_values</span>(<span class="fu">sd</span>(sample_means))),</span>
<span id="cb160-38"><a href="normal.html#cb160-38" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">xlab =</span> <span class="st">&quot;Mean length (cm)&quot;</span>, <span class="at">xlim =</span> xlims</span>
<span id="cb160-39"><a href="normal.html#cb160-39" aria-hidden="true" tabindex="-1"></a>) </span>
<span id="cb160-40"><a href="normal.html#cb160-40" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(sample_means, <span class="at">main=</span><span class="st">&quot;Sample mean QQ&quot;</span>)</span>
<span id="cb160-41"><a href="normal.html#cb160-41" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(sample_means)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:clt-examp"></span>
<img src="_main_files/figure-html/clt-examp-1.png" alt="The central limit theorem in action (when n&gt;30)." width="70%" height="70%" />
<p class="caption">
Figure 3.4: The central limit theorem in action (when n&gt;30).
</p>
</div>
<p><em>Q98. What do you notice about the location of the mean as a function of N?</em></p>
<p><em>Q99. What do you notice about the spread around the mean in each group as a function of sample size – why did the pattern you have observed occur?</em></p>
<p>You are witnessing the central limit theorem in action – the means of normally distributed numbers are, themselves, normally distributed, and the means of non-normally distributed numbers are <em>also</em> normally distributed provided the sample size is large enough. Note the relationship between the sample size and the range of values for the sample mean. How does the standard deviation of <code>sample_means</code> change with changes in <code>sample_size</code>?.</p>
<hr />
</div>
</div>
<div id="the-standard-error-of-the-mean" class="section level2 hasAnchor" number="3.8">
<h2><span class="header-section-number">3.8</span> The standard error of the mean<a href="normal.html#the-standard-error-of-the-mean" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The standard error of the mean is simply the standard deviation of sample means, of a given sample size, taken from a population. That is, it is the standard deviations calculated in the lower histogram in Fig. <a href="normal.html#fig:clt-examp">3.4</a>. It is calculated as <span class="math inline">\(SE_{\bar{y}} = \frac{sd(y)}{\sqrt{n}}\)</span>.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="normal.html#cb161-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb161-2"><a href="normal.html#cb161-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate a normally distributed population with mean mu and sd sigma</span></span>
<span id="cb161-3"><a href="normal.html#cb161-3" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb161-4"><a href="normal.html#cb161-4" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb161-5"><a href="normal.html#cb161-5" aria-hidden="true" tabindex="-1"></a>sim_obs <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="dv">10000</span>, mu, sigma)</span>
<span id="cb161-6"><a href="normal.html#cb161-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-7"><a href="normal.html#cb161-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Draw samples</span></span>
<span id="cb161-8"><a href="normal.html#cb161-8" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>, <span class="dv">30</span>, <span class="dv">100</span>) <span class="co"># size of each sample</span></span>
<span id="cb161-9"><a href="normal.html#cb161-9" aria-hidden="true" tabindex="-1"></a>num_samples <span class="ot">&lt;-</span> <span class="dv">1000</span> <span class="co"># number of samples (=repeats) for each sample size</span></span>
<span id="cb161-10"><a href="normal.html#cb161-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-11"><a href="normal.html#cb161-11" aria-hidden="true" tabindex="-1"></a>sample_mean_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">N=</span><span class="fu">rep</span>(sample_size, <span class="at">each =</span> num_samples),</span>
<span id="cb161-12"><a href="normal.html#cb161-12" aria-hidden="true" tabindex="-1"></a>                         <span class="at">id=</span><span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span>num_samples, <span class="at">times =</span> <span class="fu">length</span>(sample_size))) <span class="sc">|&gt;</span></span>
<span id="cb161-13"><a href="normal.html#cb161-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sample_mean=</span><span class="dv">0</span>)</span>
<span id="cb161-14"><a href="normal.html#cb161-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-15"><a href="normal.html#cb161-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span>(i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(sample_mean_df)) {</span>
<span id="cb161-16"><a href="normal.html#cb161-16" aria-hidden="true" tabindex="-1"></a>  sample_i <span class="ot">&lt;-</span> <span class="fu">sample</span>(sim_obs, sample_mean_df<span class="sc">$</span>N[i])</span>
<span id="cb161-17"><a href="normal.html#cb161-17" aria-hidden="true" tabindex="-1"></a>  sample_mean_df<span class="sc">$</span>sample_mean[i] <span class="ot">&lt;-</span> <span class="fu">mean</span>(sample_i)</span>
<span id="cb161-18"><a href="normal.html#cb161-18" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="normal.html#cb162-1" aria-hidden="true" tabindex="-1"></a>sample_mean_df <span class="sc">|&gt;</span></span>
<span id="cb162-2"><a href="normal.html#cb162-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">N=</span><span class="fu">factor</span>(N, <span class="at">levels=</span><span class="fu">unique</span>(N))) <span class="sc">|&gt;</span></span>
<span id="cb162-3"><a href="normal.html#cb162-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(N, sample_mean)) <span class="sc">+</span> </span>
<span id="cb162-4"><a href="normal.html#cb162-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span>mu, <span class="at">linetype=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb162-5"><a href="normal.html#cb162-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">scale=</span><span class="st">&quot;width&quot;</span>, <span class="at">draw_quantiles=</span><span class="fu">c</span>(<span class="fl">0.025</span>, <span class="fl">0.5</span>, <span class="fl">0.975</span>), <span class="at">fill=</span><span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb162-6"><a href="normal.html#cb162-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha=</span><span class="fl">0.2</span>, <span class="at">shape=</span><span class="dv">1</span>, <span class="at">width=</span><span class="fl">0.05</span>) <span class="sc">+</span> </span>
<span id="cb162-7"><a href="normal.html#cb162-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">&quot;Sample size&quot;</span>, <span class="at">y=</span><span class="fu">paste</span>(<span class="st">&quot;Means of&quot;</span>, num_samples, <span class="st">&quot;simulated samples&quot;</span>)) <span class="sc">+</span></span>
<span id="cb162-8"><a href="normal.html#cb162-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:SEM-fig"></span>
<img src="_main_files/figure-html/SEM-fig-1.png" alt="Simulated sample means." width="50%" height="50%" />
<p class="caption">
Figure 3.5: Simulated sample means.
</p>
</div>
<p><em>Q100. Calculate the theoretical standard error of the means for each <code>sample_size</code> given <code>sigma</code> and compare this with your actual standard error (=standard deviation) of sample means</em></p>
<p><em>Q101. Given what you know about the CLT, how does this change with non-normally distributed data? Try changing <code>rnorm()</code> to <code>rpois()</code></em></p>
<p><em>Q102. Change <code>sigma</code> and <code>sample_size</code> and check that the standard error estimates are in line with their true values (i.e. as determined by using the standard error formula).</em></p>
<hr />
</div>
<div id="normal-approximations-for-other-distributions" class="section level2 hasAnchor" number="3.9">
<h2><span class="header-section-number">3.9</span> Normal approximations for other distributions<a href="normal.html#normal-approximations-for-other-distributions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In earlier exercises you saw that the Poisson distribution could be used to approximate the binomial distribution. In a conceptually similar way, the normal distribution can be used to approximate the Poisson model.</p>
<div id="the-normal-approximation-of-the-poisson-distribution" class="section level3 hasAnchor" number="3.9.1">
<h3><span class="header-section-number">3.9.1</span> The Normal approximation of the Poisson distribution<a href="normal.html#the-normal-approximation-of-the-poisson-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Recall that the Poisson model takes only one parameter, the mean, and that where a variable is Poisson distributed the variance equals the mean. So if we have a variable <span class="math inline">\(y \sim Pois(10)\)</span>, the mean (say density per quadrat) is 10 and so is the variance. We now have the two parameters that define the normal distribution (the mean and variance).</p>
<p><em>Q103. For</em> <span class="math inline">\(y \sim Pois(10)\)</span> <em>write the equivalent normal distribution in standard notation.</em></p>
<p>As a rough guideline, a normal approximation is reasonable if <span class="math inline">\(\lambda \geq 30\)</span>. So <span class="math inline">\(y \sim Pois(10)\)</span> should not be approximated by the normal distribution while <span class="math inline">\(y \sim Pois(30)\)</span> could be. However, it is generally preferable to use the natural distribution for your data (e.g., a Poisson distribution for counts). The normal distribution is beneficial in some cases, but this is increasingly less so with modern methods.</p>
<p><em>Q104. For a Poisson distribution</em> <span class="math inline">\(y \sim Pois(40)\)</span> <em>define the normal approximation in the standard way.</em></p>
<p><em>Q105. Using R and referring Practical</em> <a href="binpois.html#binpois">2</a><em>, calculate</em> <span class="math inline">\(P(y_i \leq 35)\)</span> <em>from</em> <span class="math inline">\(y \sim Pois(40)\)</span> <em>(Ans = 0.242)</em></p>
<p><em>Q106. Using R, calculate</em> <span class="math inline">\(P(y_i &lt; 35)\)</span> <em>from the above normal approximation of the Poisson distribution (Ans = 0.215).</em></p>
<p><em>Q107. What do you think of the normal approximation?</em></p>
<p><em>Q108. Evaluate</em> <span class="math inline">\(P(y_i&lt;3\ |\ \lambda=5)\)</span> <em>using the Poisson model and its normal approximation.</em></p>
</div>
<div id="the-normal-approximation-of-the-binomial-distribution" class="section level3 hasAnchor" number="3.9.2">
<h3><span class="header-section-number">3.9.2</span> The normal approximation of the binomial distribution<a href="normal.html#the-normal-approximation-of-the-binomial-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Whilst we accept the fundamental difference between continuous and discrete data, in making continuous-variable measurements we inevitably allocate each measurement to a single measurement category (we are limited by our ability to measure, eg. to the nearest millimeter if using a ruler). If we wish to treat a continuous variable as a continuous variable, the number of categories between the smallest and largest measurement should be a minimum of ~30 (the upper limit doesn’t matter so much but there is no need to &gt;300). For example, suppose we were measuring fish-lengths and the min was 20 cm and the max 40 cm. That means there are 20 x 1 cm measurement units between them. This falls under our 30 unit minimum – measuring to the nearest cm would not be adequate. There are, however, 40 x 0.5 cm units between them so we could measure to the nearest 0.5 cm (we would probably use 0.1 cm though). But, even if we measure to the correct degree of precision, we are still categorising the lengths. For example, a fish of 20.5 cm actually means we think that fish was between 20.45 and 20.55 cm.</p>
<p>What is the point of this? Well, if you have a binomially distributed variable where <span class="math inline">\(n\)</span>, the number of trials, is sufficiently large (meaning the number of outcomes is large too) then the binomial distribution begins to look like the normal distribution, particularly where <span class="math inline">\(p\)</span> is somewhere near 0.5. The general guideline is that where the number of trials multiplied by the smaller of the probability of success (<span class="math inline">\(p\)</span>) or the probability of failure (<span class="math inline">\(q=1-p\)</span>) is greater than 5 then we can reasonably use the normal distribution to model the data (i.e. both <span class="math inline">\(n*p &gt; 5\)</span> and <span class="math inline">\(n*(1-p) &gt; 5\)</span>).</p>
<p>Turtles lay clutches of 40 eggs. We might be interested in predicting the number of male and female offspring. Assume the proportion that are male is 0.5. Our investigation stems from the observation that several clutches of eggs, on a particular island, contained only 10 males. We might wonder how unlikely this was by chance, assuming <span class="math inline">\(P(male)=0.5\)</span>.</p>
<p><em>Q109. Referring to Practical</em> <a href="binpois.html#binpois">2</a> <em>if necessary, use the binomial model, calculate how unusual (i.e. the probability) it is to get</em> <span class="math inline">\(\leq 10\)</span> <em>males.</em></p>
<p><em>Q110. Plot your probability (i.e. from 0 – 40 males) as a bar graph. Comment on its shape.</em></p>
<p>The variance of a binomially distributed variable is simply <span class="math inline">\(n*p*q\)</span>.</p>
<p><em>Q111. Calculate the mean and variance of this population.</em></p>
<p><em>Q112. Are</em> <span class="math inline">\(n*p\)</span> <em>and</em> <span class="math inline">\(n*(p-1)\)</span> <em>both &gt;5?</em></p>
<p><em>Q113. Given these two variables, specify the equivalent normal distribution.</em></p>
<p>We have the ‘real’ distribution <span class="math inline">\(y \sim Binom(40,0.5)\)</span> and its normal approximation. We ask what is <span class="math inline">\(P(y_i \leq 10)\)</span> given <span class="math inline">\(y \sim Binom(40, 0.5)\)</span> and given <span class="math inline">\(y \sim Norm(20, 10)\)</span>.</p>
<p><em>Q114. Calculate the Z score for 10 males then find the probability of making this observation.</em></p>
<p><em>Q115. How do the values from the different models compare?</em></p>
<hr />
</div>
</div>
<div id="conclusions-2" class="section level2 hasAnchor" number="3.10">
<h2><span class="header-section-number">3.10</span> Conclusions<a href="normal.html#conclusions-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The normal distribution is central to statistics. A huge variety of observations are reasonably approximated by the normal distribution (or can be made to be normally distributed through transformation).</p>
<p>The normal distribution can be used to assess the likelihood of a given observation, if we know the population mean and standard deviation from which it came. Furthermore, given our knowledge of the population parameter (mean and variance) we can determine values which define intervals on that population. Frequently scientists determine the values that bound 95% of their data.</p>
<p>The central limit theorem says that sample means taken from a normally distributed population will themselves be normally distributed and, in addition, means of sufficiently large samples will also be normally distributed even where the original data are not normally distributed (the sample size required depends on the extent of the skew in the original data).</p>
<p>The normal distribution is a good approximation of the Poisson distribution when lambda is large and the binomial model where the number of trials is large and the probability of success around 0.5 (i.e. the distribution of values is not too skewed).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="binpois.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="t-test.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/Sz-Tim/H2_DS_practicals/edit/BRANCH/03_normal.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
